/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vegy.bolt;

/**
 *
 * @author user09
 */
public class Uj_temek extends javax.swing.JFrame {

    /**
     * Creates new form Uj_temék
     */
    public Uj_temek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jButton_vissza = new javax.swing.JButton();
        jLabel_Termekcs1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_cikkszam = new javax.swing.JLabel();
        jLabel_termekcsoport = new javax.swing.JLabel();
        jLabel_termeknev = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_ar = new javax.swing.JLabel();
        jLabel_egyseg = new javax.swing.JLabel();
        jLabel_keszlet = new javax.swing.JLabel();
        jTextField_cikkszam = new javax.swing.JTextField();
        jTextField_termeknev = new javax.swing.JTextField();
        jTextField_ar = new javax.swing.JTextField();
        jTextField_egyseg = new javax.swing.JTextField();
        jTextField_keszlet = new javax.swing.JTextField();
        jButton_alaphelyzet = new javax.swing.JButton();
        jButton_felvetel = new javax.swing.JButton();
        jButton_modosit = new javax.swing.JButton();
        jComboBox_termekcsoport = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_vissza.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_vissza.setText("Vissza");
        jButton_vissza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_visszaActionPerformed(evt);
            }
        });

        jLabel_Termekcs1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Termekcs1.setText("Termékek:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel_cikkszam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_cikkszam.setText("Cikkszám:");

        jLabel_termekcsoport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_termekcsoport.setText("Termékcsoport:");

        jLabel_termeknev.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_termeknev.setText("Terméknév:");

        jLabel_ar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_ar.setText("Ár:");

        jLabel_egyseg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_egyseg.setText("Egység:");

        jLabel_keszlet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_keszlet.setText("Készlet:");

        jTextField_cikkszam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextField_termeknev.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextField_ar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextField_egyseg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTextField_keszlet.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton_alaphelyzet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_alaphelyzet.setText("Alaphelyzet");

        jButton_felvetel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_felvetel.setText("Felvétel");

        jButton_modosit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_modosit.setText("Módosít");
        jButton_modosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modositActionPerformed(evt);
            }
        });

        jComboBox_termekcsoport.setEditable(true);
        jComboBox_termekcsoport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Termekcs1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_alaphelyzet, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(171, 171, 171))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addComponent(jTextField_cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_termeknev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_termekcsoport, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                    .addComponent(jLabel_ar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_egyseg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_keszlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_termekcsoport, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_ar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .addComponent(jTextField_egyseg, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_keszlet, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField_termeknev, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_felvetel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283)
                        .addComponent(jButton_modosit, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)
                        .addComponent(jButton_vissza, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_Termekcs1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton_alaphelyzet, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_vissza)
                            .addComponent(jButton_felvetel)
                            .addComponent(jButton_modosit)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_termeknev)
                            .addComponent(jTextField_termeknev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_termekcsoport)
                            .addComponent(jComboBox_termekcsoport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ar)
                            .addComponent(jTextField_ar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_egyseg)
                            .addComponent(jTextField_egyseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_keszlet)
                            .addComponent(jTextField_keszlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_visszaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_visszaActionPerformed
        
        
    }//GEN-LAST:event_jButton_visszaActionPerformed

    private void jButton_modositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_modositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uj_temek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uj_temek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uj_temek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uj_temek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uj_temek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alaphelyzet;
    private javax.swing.JButton jButton_felvetel;
    private javax.swing.JButton jButton_modosit;
    private javax.swing.JButton jButton_vissza;
    private javax.swing.JComboBox<String> jComboBox_termekcsoport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Termekcs1;
    private javax.swing.JLabel jLabel_ar;
    private javax.swing.JLabel jLabel_cikkszam;
    private javax.swing.JLabel jLabel_egyseg;
    private javax.swing.JLabel jLabel_keszlet;
    private javax.swing.JLabel jLabel_termekcsoport;
    private javax.swing.JLabel jLabel_termeknev;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_ar;
    private javax.swing.JTextField jTextField_cikkszam;
    private javax.swing.JTextField jTextField_egyseg;
    private javax.swing.JTextField jTextField_keszlet;
    private javax.swing.JTextField jTextField_termeknev;
    // End of variables declaration//GEN-END:variables
}
